script: ci/travis.rb
language: ruby
sudo: false
matrix:
  include:
    - rvm: 2.0
      env: TASK=test ARCONN=mysql2
      gemfile: ci/Gemfile.activerecord-4.2.x
    - rvm: 2.1
      env: TASK=test ARCONN=mysql2
      gemfile: ci/Gemfile.activerecord-4.2.x
    - rvm: 2.2
      env: TASK=test ARCONN=mysql2
      gemfile: ci/Gemfile.activerecord-4.1.x
    - rvm: 2.2
      env: TASK=test ARCONN=sqlite3
      gemfile: ci/Gemfile.activerecord-4.2.x
    - rvm: 2.2
      env: TASK=test ARCONN=mysql2
      gemfile: ci/Gemfile.activerecord-4.2.x
    - rvm: 2.2
      env: TASK=test ARCONN=postgresql
      gemfile: ci/Gemfile.activerecord-4.2.x
  allow_failures:
    env:
      - TASK=benchmark ARCONN=mysql2
