script: ci/travis.rb
language: ruby
rvm:
  - 2.1.5
gemfile:
  - ci/Gemfile.activerecord-3.2.x
  - ci/Gemfile.activerecord-4.0.x
  - ci/Gemfile.activerecord-4.1.x
env:
  - ARCONN=sqlite3
  - ARCONN=mysql2
  - ARCONN=postgresql
